### ISSUE TITLE
Unit test API to facilitate refactoring and improve the stability

### ISSUE THREAD

**Issue by quickskape** [tsangste/ChaosSpankr.Home#8]
Currently whilst doing PRs it is laborious to test the api after each comment is fixed.
Currently I have to `curl` the api methods to test that I have not regressed the code.

I think we should add unit tests to the API to allow us to refactor and modify code without destabilising the codebase.

**Comment by ReissJarvis** [comment]
Are we going to look at different testing frameworks or do you have a framework in mind?

**Comment by quickskape** [comment]
I have used `supertest` and `mocha` for now.

I looked through a few different frameworks and they mostly seem very similar.

I like `supertest` becuase it allows us to quite quickly test our api from the top level without introducing any unneeded abstractions at this early point.

Take a look at: https://github.com/tsangste/ChaosSpankr.Server/pull/6 and let me know what you think :)
